all:
  children:
    debian:
      hosts:
        a.lx1duc.ampr.org:
        vault.lx1duc.radio:
        lx1duc-pmg.lx0duc.ampr.org:
        #pve1.lx0duc.hamnet.radio:
        dns.lx4cg.ampr.org:
        pmg.lx4cg.ampr.org:
        charlotte.rbx7.as60391.net:
        ermesinde.as60391.net:
        jean.as60391.net:
        wilhelm.rbx7.as60391.net:
        ett-sal-vps-01.acett.network:
        ett-vps-02.acett.network:
        fra-han-vps-01.acett.network:
    dns:
      hosts:
        a.lx1duc.ampr.org:
        dns.lx4cg.ampr.org:
        ermesinde.as60391.net:
        ett-sal-vps-01.acett.network:
        fra-han-vps-01.acett.network:

    docker:
      hosts:
        ett-vps-02.acett.network:

    ntp:
      hosts:
        a.lx1duc.ampr.org:
        dns.lx4cg.ampr.org:
        ermesinde.as60391.net:
        ett-sal-vps-01.acett.network:
        fra-han-vps-01.acett.network:

    crowdsec:
      hosts:
        dns.lx4cg.ampr.org:
        pmg.lx4cg.ampr.org:
        ermesinde.as60391.net:
        jean.as60391.net:

    routeros:
      hosts:
        rtr-16.lx0duc.hamnet.radio:
      vars:
        ansible_network_os: routeros
        ansible_user: ansible
  vars:
    ansible_ssh_private_key_file: /home/mstorck/.ssh/id_ed25519
    ansible_user: ansible
