---
- name: Backup ACETT RouterOS
  hosts: acett_switches
  gather_facts: yes
  connection: network_cli
  tasks:
  - name: gather export
    community.routeros.command:
      commands: /export show-sensitive
    register: export

  - debug:
      var: export.stdout_lines

#  - name: transforming export
#    set_fact:
#      export2: "{{ export | reject('match', '^#') | list }}"

  - name: store export to local file
    ansible.builtin.copy:
      content: "{{ export.stdout }}"
      dest: "{{ inventory_hostname }}"
    when: export is defined
