---
- name: sync address-list
  hosts: acett_routers-rtr
  gather_facts: no
  module_defaults:
    group/community.routeros.api:
      hostname: "{{ inventory_hostname }}"
      password: ZvQV6py9CjnEKuRW4bF2TrNYxe8qGJ37
      username: "{{ ansible_user }}"
  connection: network_cli
  tasks:
    - name: Define the list
      set_fact:
        desired_address_list:
        #Default
          - "0.0.0.0/0"
        #DARC
          - "44.31.0.0/22"
          - "192.68.17.0/24"
        #DFN
          - "134.91.0.0/16"
        #Eltrona
          - "153.94.16.0/20"
          - "153.94.16.0/22"
          - "153.94.16.0/23"
          - "153.94.18.0/23"
          - "178.249.192.0/21"
          - "178.249.192.0/23"
          - "178.249.194.0/23"
          - "185.49.244.0/22"
          - "185.108.248.0/22"
          - "192.98.120.0/21"
        #LuxembourgOnline
          - "31.172.144.0/21"
          - "83.222.32.0/19"
          - "94.103.208.0/21"
          - "94.103.208.0/20"
          - "94.103.216.0/21"
          - "185.6.232.0/22"
          - "192.160.22.0/24"
          - "195.218.0.0/21"
          - "195.218.8.0/21"
          - "195.218.16.0/21"
          - "195.218.16.0/20"
          - "195.218.24.0/21"
        #Mixvoip
          - "2.56.104.0/22"
          - "2.56.106.0/23"
          - "5.180.164.0/24"
          - "5.180.164.0/22"
          - "5.180.166.0/24"
          - "45.158.140.0/24"
          - "45.158.140.0/22"
          - "45.158.141.0/24"
          - "45.158.142.0/24"
          - "46.29.176.0/24"
          - "46.29.177.0/24"
          - "46.29.180.0/24"
          - "46.29.182.0/24"
          - "78.111.128.0/20"
          - "78.111.130.0/24"
          - "85.208.4.0/22"
          - "92.119.100.0/24"
          - "92.119.101.0/24"
          - "92.119.102.0/24"
          - "92.119.103.0/24"
          - "185.28.204.0/24"
          - "185.28.204.0/22"
          - "185.104.168.0/22"
          - "185.104.171.0/24"
          - "185.125.180.0/24"
          - "185.125.180.0/22"
          - "185.125.183.0/24"
          - "185.173.180.0/22"
          - "185.173.182.0/24"
          - "185.197.96.0/24"
          - "185.213.184.0/22"
          - "185.213.187.0/24"
          - "195.178.124.0/24"
          - "195.178.124.0/23"
          - "195.178.124.0/22"
          - "195.178.125.0/24"
          - "195.178.126.0/24"
          - "195.178.126.0/23"
          - "195.178.127.0/24"
          - "213.177.95.0/24"
        #Orange
          - "85.94.224.0/24"
          - "85.94.224.0/19"
          - "94.252.0.0/21"
          - "94.252.72.0/21"
          - "94.252.0.0/17"
        #Post Luxembourg
          - "37.157.152.0/21"
          - "78.141.128.0/18"
          - "83.99.0.0/17"
          - "87.240.192.0/18"
          - "88.207.128.0/17"
          - "107.183.0.0/17"
          - "146.0.128.0/18"
          - "146.0.212.0/22"
          - "146.0.216.0/21"
          - "178.254.64.0/18"
          - "185.104.108.0/22"
          - "188.115.0.0/18"
          - "193.168.10.0/23"
          - "193.168.14.0/23"
          - "194.154.192.0/19"
          - "195.46.224.0/19"
          - "213.135.224.0/19"
          - "213.166.32.0/19"
        #RESTENA
          - "158.64.0.0/16"
          - "185.149.136.0/22"
          - "193.168.64.0/18"
          - "193.168.80.0/24"
          - "193.168.1.0/24"
          - "192.103.2.0/24"
        #RWTH
          - "137.226.0.0/16"
        #Scaleway/Online.net
          - "51.15.0.0/16"
          - "51.15.0.0/17"
        #VisualOnline
          - "80.90.32.0/19"
          - "85.93.192.0/19"
          - "109.69.240.0/21"
          - "185.197.98.0/24"
          - "185.197.99.0/24"
          - "185.211.232.0/22"
          - "195.200.240.0/23"
          - "207.244.196.0/24"
        #VDL
          - "194.99.159.0/24"
        #Voipgate
          - "78.111.132.0/24"

    - name: get
      community.routeros.api:
        path: "ip firewall address-list"
        query: ".id address list WHERE list == V4-AL-bgp.input.accept-nlri-provider"
      register: current_address_list

    - name: Debug
      debug:
        var: current_address_list

    - name: Add missing addresses to the MikroTik address list
      community.routeros.api:
        path: "ip firewall address-list"
        add: "list=V4-AL-bgp.input.accept-nlri-provider address={{ item }}"
      loop: "{{ desired_address_list }}"
      when: "item not in current_address_list.msg | map(attribute='address') | list"
      register: res_add

    - name: get
      community.routeros.api:
        path: "ip firewall address-list"
        query: ".id address list WHERE list == V4-AL-bgp.input.accept-nlri-provider"
      register: current_address_list

    - name: remove obsolete addresses from the Mikrotik address list
      community.routeros.api:
        path: "ip firewall address-list"
        remove: "'{{ item['.id'] }}'"
      loop: "{{ current_address_list.msg }}"
      when: "item.address not in desired_address_list"
      register: res_rm

    - name: refresh BGP session with Mixvoip
      community.routeros.api:
        path: "routing bgp session"
        cmd: "refresh V4-AS206610-MixvoipBissen-1 address-family=ip"
      when: (res_add.changed is defined and res_add.changed) or (res_rm.changed is defined and res_rm.changed)

    - name: Pause for 5 minutes to build app cache
      ansible.builtin.pause:
        seconds: 25

    - name: refresh BGP session with VO
      community.routeros.api:
        path: "routing bgp session"
        cmd: "refresh V4-AS009008-VO-1 address-family=ip"
      when: (res_add.changed is defined and res_add.changed) or (res_rm.changed is defined and res_rm.changed)
