---
- name: Check and Install Updates on RouterOS
  hosts: routeros
  gather_facts: no
#  module_defaults:
#    group/community.routeros.routeros:
#      hostname: "{{ inventory_hostname }}"
#      password: ZvQV6py9CjnEKuRW4bF2TrNYxe8qGJ37
#      username: "{{ ansible_user }}"
  connection: network_cli

  tasks:
    - name: Check current RouterOS version
      community.routeros.command:
        commands:
          - "system package print"
      register: routeros_version

    - name: Display RouterOS version
      debug:
        var: routeros_version

    - name: Check for available updates
      community.routeros.command:
        commands:
          - "system package update check-for-updates"
      register: update_check

    - name: Display update check result
      debug:
        var: update_check

    - name: Install updates
      community.routeros.command:
        commands:
          - "system package update install"
      when: "'installed' in update_check.stdout"  # Only install if update is available
      register: update_install

    - name: Reboot the router after the update
      community.routeros.command:
        commands:
          - "system reboot"
      when: update_install is changed
      register: reboot

    - name: Notify about rebooting
      debug:
        msg: "RouterOS was updated and is now rebooting."
      when: reboot is changed
